name: Build Docker
on:
  workflow_dispatch:
  schedule:
    - cron:  "0 22 * * *"
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:
    types: [docker]
jobs:
  generate:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/bimberlabinternal/discvr-base
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "GH_PAT=${{ secrets.PAT }}"
          pull: true
          push: ${{github.ref == 'refs/heads/main'}}
          tags: ghcr.io/bimberlabinternal/discvr-base:nightly,ghcr.io/bimberlabinternal/discvr-base:latest
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.title=discvr-base
            org.opencontainers.image.description=The base docker image for various R packages

      - name: Trigger cellhashR Docker
        if: github.event_name != 'pull_request'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: bimberlab/cellhashR
          event-type: docker

      - name: Trigger CellMembrane Docker
        if: github.event_name != 'pull_request'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: bimberlabinternal/CellMembrane
          event-type: docker

      - name: Trigger RIRA Docker
        if: github.event_name != 'pull_request'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: bimberlab/RIRA
          event-type: docker

      - name: Trigger Rdiscvr Docker
        if: github.event_name != 'pull_request'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: bimberlabinternal/Rdiscvr
          event-type: docker

